services:
  backend:
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
  frontend:
    platform: linux/amd64
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - VITE_API_HOSTNAME=http://localhost:3000
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app